const API_LOADING_START = 'API_LOADING_START';
const API_LOADING_SUCCESS = 'API_LOADING_SUCCESS';
const API_LOADING_FAILED = 'API_LOADING_FAILED';
const NULLIFY_ERROR = 'NULLIFY_ERROR';

const AUTH_SIGN = 'AUTH_SIGN';
const AUTH_LOGOUT = 'AUTH_LOGOUT';

const GET_PRODUCTS = 'GET_PRODUCTS';

const ADD_TO_CART = 'ADD_TO_CART';
const GET_CART = 'GET_CART';

export {
  API_LOADING_START,
  API_LOADING_FAILED,
  API_LOADING_SUCCESS,
  AUTH_LOGOUT,
  AUTH_SIGN,
  NULLIFY_ERROR,
  GET_PRODUCTS,
  GET_CART,
  ADD_TO_CART,
};
